--- Seed shop listings @ 50k — item rarity common (nam + nữ), không trùng pool gacha.
--- Data: data/seed_common_50k.lua (generated by ak4y-caseOpening/tools/gen_clothing_gacha.py)

local SeedData = lib.load('data.seed_common_50k')

local function applySeed(source, forceUpdate)
    local price = math.floor(tonumber(SeedData.price) or 50000)
    local ids = SeedData.itemIds or {}
    local added, updated, skipped = 0, 0, 0

    for i = 1, #ids do
        local clothingItemId = tonumber(ids[i])
        if clothingItemId then
            local listingId = MySQL.scalar.await(
                'SELECT id FROM hgrp_clothingshop_listings WHERE clothing_item_id = ? LIMIT 1',
                { clothingItemId }
            )
            if listingId then
                if forceUpdate then
                    MySQL.update.await(
                        'UPDATE hgrp_clothingshop_listings SET price = ?, enabled = 1, sort_order = ? WHERE id = ?',
                        { price, i, listingId }
                    )
                    updated = updated + 1
                else
                    MySQL.update.await(
                        'UPDATE hgrp_clothingshop_listings SET enabled = 1 WHERE id = ? AND enabled = 0',
                        { listingId }
                    )
                    skipped = skipped + 1
                end
            else
                MySQL.insert.await(
                    [[INSERT INTO hgrp_clothingshop_listings (clothing_item_id, price, enabled, sort_order)
                      VALUES (?, ?, 1, ?)]],
                    { clothingItemId, price, i }
                )
                added = added + 1
            end
        else
            skipped = skipped + 1
        end
    end

    Catalog.invalidate()

    local msg = ('Seed shop 50k: +%d mới, %d cập nhật, %d đã có.'):format(added, updated, skipped)
    if source and source > 0 then
        exports.qbx_core:Notify(source, msg, 'success')
    end
    print(('[hgrp_clothingshop] %s'):format(msg))
    return added, updated, skipped
end

lib.addCommand('clothingshopseed50k', {
    help = 'Seed shop quần áo: item thường nam/nữ giá 50.000$ (giữ giá món đã có)',
    restricted = 'group.admin',
}, function(source)
    applySeed(source, false)
end)

lib.addCommand('clothingshopseed50kforce', {
    help = 'Seed shop quần áo — cập nhật lại giá/sort toàn bộ seed',
    restricted = 'group.admin',
}, function(source)
    applySeed(source, true)
end)

exports('seedCommonShopListings', applySeed)

CreateThread(function()
    while GetResourceState('oxmysql') ~= 'started' do Wait(200) end
    Wait(1500)
    pcall(function()
        applySeed(nil, false)
    end)
end)
