return {
  accent = '#14f66c',
  title = 'Cửa hàng quần áo',

  -- Chỉ hiện / bán item đã có trong hgrp_clothing_capture (m_hat_0_0, f_jacket_18_0, ...)
  onlyRegisteredItems = true,

  -- Ảnh quần áo (MinIO / CDN). Tên file: m_jacket_0_0.png, f_hat_11_1.png, ...
  imageBase = 'https://minio1.webtui.vn:9000/bucket-renkunji123/images/',

  -- Loại quần áo được bán (để trống / nil = tất cả adminCategories).
  -- Mỗi shop có thể override bằng shops[index].categories
  sellCategories = nil,

  --- Menu admin cấu hình catalog (panel phải Illenium) — chỉ 5 loại chính
  panelCategories = {
    {
      id = 'jacket',
      label = 'Áo khoác',
      saveLabel = 'Lưu áo khoác',
      primaryComp = 11,
      componentChecks = {
        { id = 3, label = 'Tay / body (comp 3)' },
        { id = 4, label = 'Quần / chân (comp 4)' },
        { id = 6, label = 'Giày (comp 6)' },
        { id = 8, label = 'Áo trong (comp 8)' },
      },
    },
    {
      id = 'pants',
      label = 'Quần',
      saveLabel = 'Lưu quần',
      primaryComp = 4,
      simple = true,
    },
    {
      id = 'shoes',
      label = 'Giày',
      saveLabel = 'Lưu giày',
      primaryComp = 6,
      simple = true,
    },
    {
      id = 'undershirt',
      label = 'Áo trong',
      saveLabel = 'Lưu áo trong',
      primaryComp = 8,
      overrideSlot = true,
      componentChecks = {
        { id = 3, label = 'Tay / body (comp 3)' },
        { id = 4, label = 'Quần / chân (comp 4)' },
        { id = 6, label = 'Giày (comp 6)' },
      },
    },
    {
      id = 'hands',
      label = 'Tay (Hands)',
      saveLabel = 'Lưu tay',
      primaryComp = 3,
      overrideSlot = true,
      simple = true,
    },
    {
      id = 'face',
      label = 'Đầu / Face',
      saveLabel = 'Lưu đầu (comp 0)',
      primaryComp = 0,
      simple = true,
    },
    {
      id = 'mask',
      label = 'Mặt nạ',
      saveLabel = 'Lưu mặt nạ',
      primaryComp = 1,
      maskOptions = true,
    },
    {
      id = 'armor',
      label = 'Giáp',
      saveLabel = 'Lưu giáp',
      primaryComp = 9,
      armorOptions = true,
    },
    {
      id = 'chains',
      label = 'Phụ kiện',
      saveLabel = 'Lưu phụ kiện',
      primaryComp = 7,
      simple = true,
      unisex = true,
    },
    {
      id = 'bag',
      label = 'Balo',
      saveLabel = 'Lưu balo',
      primaryComp = 5,
      simple = true,
      unisex = true,
    },
    {
      id = 'glasses',
      label = 'Kính',
      saveLabel = 'Lưu kính',
      primaryComp = 1,
      kind = 'prop',
      simple = true,
      unisex = true,
    },
    {
      id = 'hat',
      label = 'Mũ',
      saveLabel = 'Lưu mũ',
      primaryComp = 0,
      kind = 'prop',
      simple = true,
      unisex = true,
    },
  },

  --- Cấp giáp (level = trần bảo vệ khi mặc đầy độ bền)
  armorTiers = {
    { tier = 1, level = 100, label = 'Cơ bản · 100' },
    { tier = 2, level = 150, label = 'Chuyên dụng · 150' },
    { tier = 3, level = 200, label = 'Hạng nặng · 200' },
    { tier = 4, level = 300, label = 'Đặc biệt · 300' },
  },

  --- Menu admin cấu hình shop (tab Nam/Nữ + danh mục bên dưới)
  adminCategories = {
    { id = 'pants', label = 'Quần' },
    { id = 'undershirt', label = 'Áo trong' },
    { id = 'hands', label = 'Tay (Hands)' },
    { id = 'jacket', label = 'Áo khoác' },
    { id = 'tattoo', label = 'Hình xăm' },
    { id = 'shoes', label = 'Giày' },
    { id = 'face', label = 'Đầu / Face' },
    { id = 'mask', label = 'Mặt nạ' },
    { id = 'armor', label = 'Giáp' },
    { id = 'chains', label = 'Phụ kiện' },
    { id = 'glasses', label = 'Kính' },
    { id = 'bag', label = 'Balo' },
    { id = 'hat', label = 'Mũ' },
  },

  rarities = {
    { id = 'common', label = 'Thường', color = '#94a3b8' },
    { id = 'uncommon', label = 'Hiếm', color = '#3dba4e' },
    { id = 'rare', label = 'Rất hiếm', color = '#3b82f6' },
    { id = 'legendary', label = 'Huyền thoại', color = '#e8a317' },
    { id = 'mythical', label = 'Thần thoại', color = '#ef4444' },
  },

  --- Tag loại đồ (hiển thị / lọc shop admin)
  itemTags = {
    { id = 'shirt', label = 'Áo' },
    { id = 'pants', label = 'Quần' },
    { id = 'dress', label = 'Đầm' },
    { id = 'tattoo', label = 'Hình xăm' },
    { id = 'mask', label = 'Mặt nạ' },
    { id = 'bag', label = 'Balo' },
    { id = 'shoes', label = 'Giày' },
    { id = 'accessory', label = 'Phụ kiện' },
    { id = 'other', label = 'Khác' },
  },

  admin = {
    command = 'clothingshopadmin',
    configCommand = 'clothingconfigadmin',
    ace = 'group.admin',
    --- true = catalog/listing qua DB + admin panel. false = chỉ đọc shops[].items trong config.
    dbOverridesConfig = false,
  },

  --- Tạo item ox_inventory theo metadata (jacket/pants + drawable + gender) thay vì item clothing key
  useGenericMetadata = true,

  -- focus: 'head' | 'chest' | 'pelvis' | 'feet' — xương neo camera
  -- dist/height/lookZ: offset quanh điểm focus (không phải offset từ chân ped)
  camera = {
    focus = 'chest',
    dist = 1.55,
    height = 0.14,
    lookZ = 0.0,
    fov = 35.0,
    orbitDeg = 35.0,
  },

  -- kind: 'component' | 'prop'
  -- slot: component_id hoặc prop_id (GTA)
  categories = {
    {
      id = 'hat',
      label = 'Mũ',
      kind = 'prop',
      slot = 0,
      camera = { focus = 'head', dist = 0.92, height = 0.1, lookZ = 0.04, fov = 30.0, orbitDeg = 35.0 },
    },
    {
      id = 'glasses',
      label = 'Kính',
      kind = 'prop',
      slot = 1,
      camera = { focus = 'head', dist = 0.78, height = 0.04, lookZ = 0.0, fov = 28.0, orbitDeg = 35.0 },
    },
    {
      id = 'mask',
      label = 'Mặt nạ',
      kind = 'component',
      slot = 1,
      camera = { focus = 'head', dist = 0.85, height = 0.04, lookZ = 0.0, fov = 30.0, orbitDeg = 35.0 },
    },
    {
      id = 'jacket',
      label = 'Áo khoác',
      kind = 'component',
      slot = 11,
      camera = { focus = 'chest', dist = 1.5, height = 0.18, lookZ = 0.06, fov = 36.0, orbitDeg = 35.0 },
    },
    {
      id = 'tattoo',
      label = 'Hình xăm',
      kind = 'component',
      slot = 11,
      camera = { focus = 'chest', dist = 1.5, height = 0.18, lookZ = 0.06, fov = 36.0, orbitDeg = 35.0 },
    },
    {
      id = 'undershirt',
      label = 'Áo trong',
      kind = 'component',
      slot = 8,
      camera = { focus = 'chest', dist = 1.42, height = 0.02, lookZ = -0.04, fov = 36.0, orbitDeg = 35.0 },
    },
    {
      id = 'pants',
      label = 'Quần',
      kind = 'component',
      slot = 4,
      camera = { focus = 'pelvis', dist = 1.65, height = 0.12, lookZ = -0.08, fov = 38.0, orbitDeg = 35.0 },
    },
    {
      id = 'shoes',
      label = 'Giày',
      kind = 'component',
      slot = 6,
      camera = { focus = 'feet', dist = 1.25, height = 0.42, lookZ = 0.06, fov = 32.0, orbitDeg = 35.0 },
    },
    {
      id = 'bag',
      label = 'Balo',
      kind = 'component',
      slot = 5,
      camera = { focus = 'chest', dist = 1.55, height = 0.1, lookZ = 0.0, fov = 36.0, orbitDeg = 185.0 },
    },
    {
      id = 'hands',
      label = 'Tay (Hands)',
      kind = 'component',
      slot = 3,
      camera = { focus = 'chest', dist = 1.42, height = 0.08, lookZ = 0.0, fov = 36.0, orbitDeg = 35.0 },
    },
    {
      id = 'face',
      label = 'Đầu / Face',
      kind = 'component',
      slot = 0,
      camera = { focus = 'head', dist = 0.85, height = 0.04, lookZ = 0.0, fov = 30.0, orbitDeg = 35.0 },
    },
    {
      id = 'armor',
      label = 'Giáp',
      kind = 'component',
      slot = 9,
      camera = { focus = 'chest', dist = 1.5, height = 0.14, lookZ = 0.04, fov = 36.0, orbitDeg = 35.0 },
    },
    {
      id = 'chains',
      label = 'Phụ kiện',
      kind = 'component',
      slot = 7,
      camera = { focus = 'chest', dist = 1.35, height = 0.06, lookZ = 0.0, fov = 34.0, orbitDeg = 35.0 },
    },
  },

  defaultPrices = {
    hat = 120,
    glasses = 80,
    mask = 150,
    jacket = 450,
    tattoo = 50,
    undershirt = 200,
    pants = 350,
    shoes = 280,
    bag = 220,
    chains = 180,
    face = 0,
  },

  -- Override giá theo drawable
  -- priceOverrides = { jacket = { male = { [12] = 1200 }, female = {} } }
  priceOverrides = {},

  -- Legacy: danh sách chung (dùng khi shop không có block items riêng).
  items = {},

  -- Mỗi shop: currency + danh sách đồ riêng (shops[].items).
  shops = {
    {
      key = 'clothing_normal',
      title = 'Quần áo bình dân',
      currency = 'cash',
      illeniumStoreIndex = 2,
      blipLabel = 'Cửa hàng quần áo',
      items = {
        jacket = {
          female = {
            { item = 'f_jacket_1223_0', label = 'Black dress', rarity = 'rare', price = 500000 },
            { item = 'f_jacket_1223_1', label = 'Black dress', rarity = 'rare', price = 500000 },
            { item = 'f_jacket_1223_2', label = 'Black dress', rarity = 'rare', price = 500000 },
            { item = 'f_jacket_1229_0', label = '@ City', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1229_2', label = '@ City', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1229_3', label = '@ City', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1231_0', label = 'Princess', rarity = 'rare', price = 500000 },
            { item = 'f_jacket_1231_1', label = 'Princess', rarity = 'rare', price = 500000 },
            { item = 'f_jacket_1232_0', label = 'thing Shirt', rarity = 'rare', price = 200000 },
            { item = 'f_jacket_1232_1', label = 'thing Shirt', rarity = 'rare', price = 200000 },
            { item = 'f_jacket_1237_0', label = 'Simple dress', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1237_1', label = 'Simple dress', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1237_2', label = 'Simple dress', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1237_3', label = 'Simple dress', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1237_4', label = 'Simple dress', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1237_5', label = 'Simple dress', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1241_0', label = 'farming city', rarity = 'rare', price = 50000 },
            { item = 'f_jacket_1241_1', label = 'farming city', rarity = 'rare', price = 50000 },
            { item = 'f_jacket_1241_2', label = 'farming city', rarity = 'rare', price = 50000 },
            { item = 'f_jacket_1241_3', label = 'farming city', rarity = 'rare', price = 50000 },
            { item = 'f_jacket_1241_4', label = 'farming city', rarity = 'rare', price = 50000 },
            { item = 'f_jacket_1241_5', label = 'farming city', rarity = 'rare', price = 50000 },
            { item = 'f_jacket_1242_0', label = 'Cute Teen', rarity = 'rare', price = 500000 },
            { item = 'f_jacket_1242_1', label = 'Cute Teen', rarity = 'rare', price = 500000 },
            { item = 'f_jacket_1244_0', label = 'Flower garden', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1244_1', label = 'Flower garden', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1248_0', label = 'Girl beach', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1248_1', label = 'Girl beach', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1250_0', label = 'Pinkgirl', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1250_1', label = 'Pinkgirl', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1250_2', label = 'Pinkgirl', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1250_3', label = 'Pinkgirl', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1250_4', label = 'Pinkgirl', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1251_0', label = 'royalCity', rarity = 'rare', price = 100000 },
            { item = 'f_jacket_1251_1', label = 'royalCity', rarity = 'rare', price = 100000 },
          },
          male = {
            { item = 'm_jacket_1124_0', label = 'Mùa thu ấm áp', rarity = 'rare', price = 100000 },
            { item = 'm_jacket_1124_1', label = 'Mùa thu ấm áp', rarity = 'rare', price = 100000 },
            { item = 'm_jacket_1129_0', label = 'Lịch lãm', rarity = 'rare', price = 100000 },
            { item = 'm_jacket_1129_1', label = 'Lịch lãm', rarity = 'rare', price = 100000 },
            { item = 'm_jacket_1130_0', label = 'Nổi Loạn', rarity = 'rare', price = 100000 },
            { item = 'm_jacket_1130_1', label = 'Nổi Loạn', rarity = 'rare', price = 100000 },
            { item = 'm_jacket_1130_2', label = 'Nổi Loạn', rarity = 'rare', price = 100000 },
            { item = 'm_jacket_1133_0', label = 'The G', rarity = 'rare', price = 100000 },
            { item = 'm_jacket_1133_1', label = 'The G', rarity = 'rare', price = 100000 },
          },
        },
        pants = {
          female = {
            { item = 'f_pants_376_0', label = 'Baggy Pant', rarity = 'rare', price = 100000 },
            { item = 'f_pants_380_0', label = 'Cute Pant', rarity = 'rare', price = 100000 },
          },
          male = {
            { item = 'm_pants_426_0', label = 'BagBaggy', rarity = 'rare', price = 200000 },
            { item = 'm_pants_426_1', label = 'BagBaggy', rarity = 'rare', price = 200000 },
            { item = 'm_pants_428_1', label = 'BadWord', rarity = 'rare', price = 100000 },
            { item = 'm_pants_428_2', label = 'BadWord', rarity = 'rare', price = 100000 },
            { item = 'm_pants_428_3', label = 'BadWord', rarity = 'rare', price = 100000 },
          },
        },
        shoes = {
          male = {
            { item = 'm_shoes_350_0', label = 'Sandal dog', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_350_1', label = 'Sandal dog', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_351_0', label = 'ShortBoot', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_351_1', label = 'ShortBoot', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_352_0', label = 'JodanCute', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_352_1', label = 'JodanCute', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_352_2', label = 'JodanCute', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_352_3', label = 'JodanCute', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_352_4', label = 'JodanCute', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_353_0', label = 'crodo2', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_354_0', label = 'Sandal3', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_355_0', label = 'Sandal2', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_356_0', label = 'Sandal1', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_357_0', label = 'Sandal', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_358_0', label = 'crodo', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_358_1', label = 'crodo', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_359_0', label = 'Gucci', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_359_1', label = 'Gucci', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_360_0', label = '3lineblack', rarity = 'rare', price = 100000 },
            { item = 'm_shoes_360_1', label = '3lineblack', rarity = 'rare', price = 100000 },
          },
        },
      },
    },
    {
      key = 'clothing_premium',
      title = 'Boutique cao cấp',
      currency = 'v_medal',
      illeniumStoreIndex = 6,
      blipLabel = 'Boutique cao cấp',
      items = {
        jacket = {
          female = {
            { item = 'f_jacket_1228_0', label = 'Princess @', rarity = 'rare', price = 150 },
            { item = 'f_jacket_1228_1', label = 'Princess @', rarity = 'rare', price = 150 },
            { item = 'f_jacket_1230_0', label = 'Bag Jean girl', rarity = 'rare', price = 150 },
            { item = 'f_jacket_1230_1', label = 'Bag Jean girl', rarity = 'rare', price = 150 },
            { item = 'f_jacket_1230_2', label = 'Bag Jean girl', rarity = 'rare', price = 150 },
            { item = 'f_jacket_1233_0', label = 'Prety jean dress', rarity = 'rare', price = 150 },
            { item = 'f_jacket_1233_1', label = 'Prety jean dress', rarity = 'rare', price = 150 },
            { item = 'f_jacket_1234_0', label = 'Simple City dress', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1234_1', label = 'Simple City dress', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1234_2', label = 'Simple City dress', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1234_3', label = 'Simple City dress', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1234_4', label = 'Simple City dress', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1234_5', label = 'Simple City dress', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1238_0', label = 'Hurry Morning', rarity = 'rare', price = 150 },
            { item = 'f_jacket_1238_1', label = 'Hurry Morning', rarity = 'rare', price = 150 },
            { item = 'f_jacket_1239_0', label = 'MDN Girl', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1239_1', label = 'MDN Girl', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1240_0', label = 'Bayby boo', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1240_1', label = 'Bayby boo', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1240_2', label = 'Bayby boo', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1243_0', label = 'CowGirl', rarity = 'mythical', price = 150 },
            { item = 'f_jacket_1243_1', label = 'CowGirl', rarity = 'mythical', price = 150 },
            { item = 'f_jacket_1245_0', label = 'Gothy Royal', rarity = 'rare', price = 150 },
            { item = 'f_jacket_1246_0', label = 'Sexy Sleeping', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1246_1', label = 'Sexy Sleeping', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1246_2', label = 'Sexy Sleeping', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1246_3', label = 'Sexy Sleeping', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1246_4', label = 'Sexy Sleeping', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1247_0', label = 'Gothy Black', rarity = 'rare', price = 150 },
            { item = 'f_jacket_1247_1', label = 'Gothy Black', rarity = 'rare', price = 150 },
            { item = 'f_jacket_1249_0', label = 'Slepping PInk', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1249_1', label = 'Slepping PInk', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1252_0', label = 'Pinkgirl', rarity = 'rare', price = 50 },
            { item = 'f_jacket_1252_1', label = 'Pinkgirl', rarity = 'rare', price = 50 },
          },
          male = {
            { item = 'm_jacket_1125_0', label = 'Mùa thu ấm áp', rarity = 'rare', price = 50 },
            { item = 'm_jacket_1125_1', label = 'Mùa thu ấm áp', rarity = 'rare', price = 50 },
            { item = 'm_jacket_1128_0', label = 'BadboyVRP', rarity = 'rare', price = 50 },
            { item = 'm_jacket_1128_1', label = 'BadboyVRP', rarity = 'rare', price = 50 },
            { item = 'm_jacket_1128_2', label = 'BadboyVRP', rarity = 'rare', price = 50 },
            { item = 'm_jacket_1132_0', label = 'Haft of life', rarity = 'rare', price = 50 },
            { item = 'm_jacket_1132_1', label = 'Haft of life', rarity = 'rare', price = 50 },
            { item = 'm_jacket_1134_0', label = 'White Vest', rarity = 'rare', price = 50 },
            { item = 'm_jacket_1134_1', label = 'White Vest', rarity = 'rare', price = 50 },
          },
        },
        tattoo = {
          male = {
            -- Hands
            { item = 'm_hands_303_0', label = 'Old yakuya tatto', rarity = 'mythical', price = 250 },
            { item = 'm_hands_303_1', label = 'Old yakuya tatto', rarity = 'mythical', price = 350 },
            { item = 'm_hands_303_2', label = 'Old yakuya tatto', rarity = 'mythical', price = 150 },
            { item = 'm_hands_302_0', label = 'Dragon yakuya tatto', rarity = 'mythical', price = 1150 },
            { item = 'm_hands_301_0', label = 'Oni yakuya tatto', rarity = 'mythical', price = 550 },
            { item = 'm_hands_300_0', label = 'Bad oni yakuya tatto', rarity = 'mythical', price = 950 },
            { item = 'm_hands_299_0', label = 'Legend god tatto', rarity = 'mythical', price = 150 },
            { item = 'm_hands_298_0', label = 'Full wing tatto', rarity = 'mythical', price = 50 },
            { item = 'm_hands_297_0', label = 'Samurai demon tatto', rarity = 'mythical', price = 250 },
            { item = 'm_hands_296_0', label = 'Giao long tatto', rarity = 'mythical', price = 250 },
            { item = 'm_hands_294_0', label = 'Spring Samu tatto', rarity = 'mythical', price = 350 },
            { item = 'm_hands_285_0', label = 'Art tatto', rarity = 'mythical', price = 150 },
            { item = 'm_hands_284_0', label = 'Natra tatto', rarity = 'mythical', price = 150 },
            { item = 'm_hands_283_0', label = 'Oni wing tatto', rarity = 'mythical', price = 250 },
            { item = 'm_hands_281_0', label = 'Hkug tatto', rarity = 'mythical', price = 950 },
            { item = 'm_hands_279_0', label = 'Oni white tatto', rarity = 'mythical', price = 250 },
            { item = 'm_hands_277_0', label = 'HellOni tatto', rarity = 'mythical', price = 250 },
            { item = 'm_hands_276_0', label = 'OniGra tatto', rarity = 'mythical', price = 550 },
            { item = 'm_hands_275_0', label = 'ZhungQuy tatto', rarity = 'mythical', price = 350 },
            -- Jacket tattoos
            { item = 'm_jacket_19_0', label = 'Yakuyaboss Tatto', rarity = 'mythical', price = 50 },
            { item = 'm_jacket_20_0', label = 'Oni tatto', rarity = 'mythical', price = 50 },
            { item = 'm_jacket_1126_0', label = 'Tatto V', rarity = 'mythical', price = 450 },
            { item = 'm_jacket_1126_1', label = 'Tatto V', rarity = 'mythical', price = 150 },
            { item = 'm_jacket_1123_1', label = 'Full Body tatto', rarity = 'mythical', price = 950 },
            { item = 'm_jacket_1123_2', label = 'Full Body tatto', rarity = 'mythical', price = 650 },
            { item = 'm_jacket_1123_3', label = 'Full Body tatto', rarity = 'mythical', price = 150 },
            { item = 'm_jacket_1123_4', label = 'Full Body tatto', rarity = 'mythical', price = 350 },
            { item = 'm_jacket_1123_5', label = 'Full Body tatto', rarity = 'mythical', price = 350 },
            { item = 'm_jacket_1123_6', label = 'Full Body tatto', rarity = 'mythical', price = 350 },
            { item = 'm_jacket_1131_0', label = 'Funny tatto', rarity = 'mythical', price = 1150 },
            { item = 'm_jacket_1131_1', label = 'Funny tatto', rarity = 'mythical', price = 1150 },
            { item = 'm_jacket_1131_2', label = 'Funny tatto', rarity = 'mythical', price = 1150 },
            { item = 'm_jacket_1131_3', label = 'Funny tatto', rarity = 'mythical', price = 1150 },
            -- Pants tattoos
            { item = 'm_pants_424_0', label = 'Yakuya Boss Tatto', rarity = 'mythical', price = 550 },
            { item = 'm_pants_423_0', label = 'Mythic God Tatto', rarity = 'mythical', price = 150 },
            { item = 'm_pants_421_0', label = 'Samurai Tatto', rarity = 'mythical', price = 350 },
            { item = 'm_pants_419_0', label = 'Legend of JP Tatto', rarity = 'mythical', price = 350 },
            { item = 'm_pants_405_0', label = 'Oni Tatto', rarity = 'mythical', price = 450 },
            { item = 'm_pants_404_0', label = 'Phuong hoang Tatto', rarity = 'mythical', price = 250 },
          },
        },
        pants = {
          male = {
            { item = 'm_pants_429_0', label = 'Legend God', rarity = 'rare', price = 50 },
            { item = 'm_pants_429_1', label = 'Legend God', rarity = 'rare', price = 50 },
            { item = 'm_pants_429_2', label = 'Legend God', rarity = 'rare', price = 50 },
            { item = 'm_pants_429_3', label = 'Legend God', rarity = 'rare', price = 50 },
            { item = 'm_pants_431_0', label = 'TBaggy', rarity = 'rare', price = 150 },
            { item = 'm_pants_433_0', label = 'BadWord', rarity = 'rare', price = 150 },
          },
        },
        shoes = {
          male = {
            { item = 'm_shoes_347_0', label = 'Big Shoes', rarity = 'rare', price = 50 },
            { item = 'm_shoes_349_0', label = 'jodan dog', rarity = 'rare', price = 50 },
          },
        },
      },
    },
  },
}

